version: '2.22.0'

services:
  urlshortener:
    container_name: url_Shortener
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16.0
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d server -U sasha"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
