// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: api/urlshortener.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenLongRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LongUrl string `protobuf:"bytes,1,opt,name=longUrl,proto3" json:"longUrl,omitempty"`
}

func (x *ShortenLongRequest) Reset() {
	*x = ShortenLongRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_urlshortener_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenLongRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenLongRequest) ProtoMessage() {}

func (x *ShortenLongRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_urlshortener_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenLongRequest.ProtoReflect.Descriptor instead.
func (*ShortenLongRequest) Descriptor() ([]byte, []int) {
	return file_api_urlshortener_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenLongRequest) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

type ShortenLongResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=shortUrl,proto3" json:"shortUrl,omitempty"`
}

func (x *ShortenLongResponse) Reset() {
	*x = ShortenLongResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_urlshortener_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenLongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenLongResponse) ProtoMessage() {}

func (x *ShortenLongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_urlshortener_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenLongResponse.ProtoReflect.Descriptor instead.
func (*ShortenLongResponse) Descriptor() ([]byte, []int) {
	return file_api_urlshortener_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenLongResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type GetLongRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=shortUrl,proto3" json:"shortUrl,omitempty"`
}

func (x *GetLongRequest) Reset() {
	*x = GetLongRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_urlshortener_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLongRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLongRequest) ProtoMessage() {}

func (x *GetLongRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_urlshortener_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLongRequest.ProtoReflect.Descriptor instead.
func (*GetLongRequest) Descriptor() ([]byte, []int) {
	return file_api_urlshortener_proto_rawDescGZIP(), []int{2}
}

func (x *GetLongRequest) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type GetLongResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LongUrl string `protobuf:"bytes,1,opt,name=longUrl,proto3" json:"longUrl,omitempty"`
}

func (x *GetLongResponse) Reset() {
	*x = GetLongResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_urlshortener_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLongResponse) ProtoMessage() {}

func (x *GetLongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_urlshortener_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLongResponse.ProtoReflect.Descriptor instead.
func (*GetLongResponse) Descriptor() ([]byte, []int) {
	return file_api_urlshortener_proto_rawDescGZIP(), []int{3}
}

func (x *GetLongResponse) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

var File_api_urlshortener_proto protoreflect.FileDescriptor

var file_api_urlshortener_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x22, 0x2e, 0x0a, 0x12, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x4c, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x6c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c,
	0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x22, 0x31, 0x0a, 0x13, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x4c, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x2c, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x4c, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x2b, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4c, 0x6f,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f,
	0x6e, 0x67, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x6e,
	0x67, 0x55, 0x72, 0x6c, 0x32, 0xae, 0x01, 0x0a, 0x0c, 0x55, 0x72, 0x6c, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x65, 0x6e, 0x65, 0x72, 0x12, 0x54, 0x0a, 0x0b, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x4c, 0x6f, 0x6e, 0x67, 0x12, 0x20, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x4c, 0x6f, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x4c, 0x6f, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x07, 0x47,
	0x65, 0x74, 0x4c, 0x6f, 0x6e, 0x67, 0x12, 0x1c, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_urlshortener_proto_rawDescOnce sync.Once
	file_api_urlshortener_proto_rawDescData = file_api_urlshortener_proto_rawDesc
)

func file_api_urlshortener_proto_rawDescGZIP() []byte {
	file_api_urlshortener_proto_rawDescOnce.Do(func() {
		file_api_urlshortener_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_urlshortener_proto_rawDescData)
	})
	return file_api_urlshortener_proto_rawDescData
}

var file_api_urlshortener_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_urlshortener_proto_goTypes = []interface{}{
	(*ShortenLongRequest)(nil),  // 0: urlshortener.ShortenLongRequest
	(*ShortenLongResponse)(nil), // 1: urlshortener.ShortenLongResponse
	(*GetLongRequest)(nil),      // 2: urlshortener.GetLongRequest
	(*GetLongResponse)(nil),     // 3: urlshortener.GetLongResponse
}
var file_api_urlshortener_proto_depIdxs = []int32{
	0, // 0: urlshortener.UrlShortener.ShortenLong:input_type -> urlshortener.ShortenLongRequest
	2, // 1: urlshortener.UrlShortener.GetLong:input_type -> urlshortener.GetLongRequest
	1, // 2: urlshortener.UrlShortener.ShortenLong:output_type -> urlshortener.ShortenLongResponse
	3, // 3: urlshortener.UrlShortener.GetLong:output_type -> urlshortener.GetLongResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_urlshortener_proto_init() }
func file_api_urlshortener_proto_init() {
	if File_api_urlshortener_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_urlshortener_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortenLongRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_urlshortener_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortenLongResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_urlshortener_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLongRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_urlshortener_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLongResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_urlshortener_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_urlshortener_proto_goTypes,
		DependencyIndexes: file_api_urlshortener_proto_depIdxs,
		MessageInfos:      file_api_urlshortener_proto_msgTypes,
	}.Build()
	File_api_urlshortener_proto = out.File
	file_api_urlshortener_proto_rawDesc = nil
	file_api_urlshortener_proto_goTypes = nil
	file_api_urlshortener_proto_depIdxs = nil
}
